export type CollegueType = {
  area: string;
  email: string;
  gitHub: string;
  highlighted: boolean;
  imagePortraitUrl: string;
  imageWallOfLeetUrl: string;
  linkedIn: string;
  mainText: string;
  manager: string;
  name: string;
  office: string;
  orgUnit: string;
  phoneNumber: string;
  primaryRole: string;
  published: true;
  secondaryRole: string;
  stackOverflow: string;
  twitter: string;
};
